stages:
  - build_and_deploy

deploy_proyek:
  stage: build_and_deploy
  tags:
    - nodejs
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  script:
    - echo "🚀 Memulai proses kilat..."
    
    # 1. Install & Build di Robot Runner
    - npm ci --prefer-offline
    - npm run build
    
    # 2. Kirim file TANPA -v dan EXCLUDE node_modules
    # Pakai -az saja (a=archive, z=compress). Tanpa 'v' agar log tidak penuh.
    - rsync -az --delete --exclude '.git' --exclude 'node_modules' ./ root@192.168.1.157:/www/wwwroot/gameforsmartNewUI/
    
    # 3. Server aaPanel cuma install yang penting (Production) & Restart
    - ssh -o StrictHostKeyChecking=no root@192.168.1.157 "
        cd /www/wwwroot/gameforsmartNewUI && 
        npm install --production && 
        pm2 startOrReload ecosystem.config.js --update-env &&
        echo '✅ Deploy Berhasil!'
      "
  only:
    - main