-- =============================================
-- MIGRATION: Recreate Notifications Table
-- =============================================
-- Warning: This will drop the existing notifications table and lose data.

DROP TABLE IF EXISTS notifications;

CREATE TABLE notifications (
    id TEXT PRIMARY KEY, -- ID generated by user trigger (XID/CUID format)
    user_id TEXT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE, -- Recipient
    actor_id TEXT REFERENCES public.profiles(id) ON DELETE SET NULL, -- Sender
    type TEXT NOT NULL, -- sessionFriend, sessionGroup, friend, group, admin
    entity_type TEXT NOT NULL, -- session, friend, group, admin
    entity_id TEXT, -- ID of the session or group
    status TEXT, -- null, 'accepted', or 'rejected'
    content JSONB, -- JSONB for admin messages etc
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Optimize queries for fetching user notifications
CREATE INDEX idx_notifications_user_id ON notifications(user_id);
CREATE INDEX idx_notifications_created_at ON notifications(created_at DESC);
